sudo: required
language: python
python:
- '2.7'
addons:
  apt:
    packages:
    - docker-ce
branches:
  only:
  - master
install:
- git remote -v
script:
- "./get_image.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_6e92f7424b46_key -iv $encrypted_6e92f7424b46_iv
  -in .travis/conf.tar.gz.enc -out ~/conf.tar.gz -d
- mkdir -p ~/.docker
- mkdir -p ~/.ssh
- tar xf ~/conf.tar.gz -C ~
- mv ~/id_rsa ~/.ssh/id_rsa
- mv ~/config.json ~/.docker/config.json
- chmod 600 ~/.ssh/id_rsa
- chmod 600 ~/.docker/config.json
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
